:::{.nonincremental}
:::: {.callout-tip collapse="true" icon=false}
## Facultatif : Déploiement continu d'un modèle ML en tant qu'API

Précedement, vous avez déployé votre modèle manuellement. Grâce à `ArgoCD` il est possible de déployer un modèle de manière continu, ainsi chaque modification d'un fichier présent dans le dossier `kubernetes/` va entrainer le redéploiement automatique en se synchronisation avec le remote de votre dépôt Git. Pour vous en convaincre, suivez les étapes ci dessous :

1. On suppose que vous avez déjà effectuer les 4 premiers points de l'application 3. 

6. Accédez à votre API en utilisant l'URL définie dans votre fichier `ingress.yml`.
7. Affichez la documentation de votre API en ajoutant `/docs` à votre URL.
8. Testez votre API !
9. Réexécutez un nouveau modèle et déployez ce nouveau modèle dans votre API

<details>
<summary>
    <font size=\"3\" color=\"darkgreen\"><b>Cliquez pour voir les étapes </b></font>
</summary>

1. Exécutez un modèle.
2. Enregistrez le modèle.
3. Ajustez votre variable d'environnement `MLFLOW_MODEL_NAME` ou `MLFLOW_MODEL_VERSION` (si vous n'avez pas modifié le nom du modèle) dans le fichier `deployment.yml`.
4. Appliquez les nouveaux contrats `Kubernetes` pour mettre à jour l'API


```shell
kubectl apply -f formation-mlops/kubernetes/
```

5. Rafraîchissez votre API et vérifiez sur la page d'accueil qu'elle est désormais basée sur la nouvelle version du modèle.

</details>

::::

:::
