apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: model-training-workflow
spec:
  entrypoint: main
  arguments:
    parameters:
      # The MLflow tracking server is responsable to log the hyper-parameter and model metrics.
      - name: mlflow-tracking-uri
        value: 'https://user-avouacr-299568.user.lab.sspcloud.fr/'
      - name: mlflow-experiment-name
        value: "my-experiment"
      - name: code-source-repo
        value: "https://github.com/InseeFrLab/formation-mlops.git"
      - name: model-training-conf-list
        value: |
          [
            { "dim": 150, "maxn": 4 },
            { "dim": 120, "maxn": 4 },
            { "dim": 120, "maxn": 5 }
          ]
 

  templates:
    # Entrypoint DAG template
    - name: main
      dag:
        tasks:
          # Task 0: Start pipeline
          - name: start-pipeline
            template: start-pipeline-wt
          # Task 1: Train model with given params
          - name: train-model-with-params
            dependencies: [ start-pipeline ]
            template: run-model-training-wt
            arguments:
              parameters:
                - name: dim
                  value: "{{item.dim}}"
                - name: maxn
                  value: "{{item.maxn}}"
            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.model-training-conf-list}}"

    # Now task container templates are defined
    # Worker template for task 0 : start-pipeline
    - name: start-pipeline-wt
      inputs:
      container:
        image: busybox
        command: [ sh, -c ]
        args: [ "echo Starting pipeline" ]

    # Worker template for task-1 : train model with params
    - name: run-model-training-wt
      inputs:
        parameters:
          - name: dim
          - name: maxn
      container:
        image: inseefrlab/mlflow:v2.2.2
        command: [sh, -c]
        args: ["mlflow run $CODE_SOURCE_URI 
                --version parallel-training
                -P remote_server_uri=$MLFLOW_TRACKING_URI
                -P experiment_name=$MLFLOW_EXPERIMENT_NAME
                -P dim={{inputs.parameters.dim}}
                -P maxn={{inputs.parameters.maxn}}"]
        env:
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: "{{workflow.parameters.aws-default-region}}"
          - name: AWS_S3_ENDPOINT
            value: "{{workflow.parameters.aws-s3-endpoint}}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: MLFLOW_TRACKING_URI
            value: "{{workflow.parameters.mlflow-tracking-uri}}"
          - name: MLFLOW_EXPERIMENT_NAME
            value: "{{workflow.parameters.mlflow-experiment-name}}"
          - name: CODE_SOURCE_URI
            value: "{{workflow.parameters.code-source-repo}}"
