## Context

- [**NACE**]{.orange}
  - European standard classification of productive [**economic activities**]{.blue2}
  - [**Hierarchical structure**]{.blue2} with 4 levels and 615 codes

- At Insee, previously handled by an outdated [**rule-based**]{.orange} algorithm

- [**Common problematic**]{.orange} to many National Statistical Institutes

## FastText model {background-image="img/diag-fasttext.png" background-size="95%" background-position="50% 85%"}

::: {.nonincremental}

- [**"Bag of n-gram model"**]{.orange} : embeddings for words but also n-gram of words and characters

- Very [**simple**]{.orange} and [**fast**]{.orange} model

:::


## Data used {.scrollable}

::: {.panel-tabset}

### Slide 

- A simple use-case with only [**2 variables**]{.orange}:
  - [**Textual description**]{.blue2} of the activity – [text]{.green2}
  - [**True NACE code**]{.blue2} labelised by the rule-based engine – [nace]{.green2} (732 modalities)

- Standard [**preprocessing**]{.orange}:
  - lowercasing
  - punctuation removal
  - number removal
  - stopwords removal
  - stemming
  - ...


### Raw

```{ojs}
viewof table_data = Inputs.table(transpose(data_raw), {
    rows: 22
})
```

### Preprocessed

```{ojs}
viewof table_data_prepro = Inputs.table(transpose(data_prepro), {
    rows: 22
})
```

:::

## MLflow with a non standard framework

::: {.nonincremental}

:::: {.fragment fragment-index=1}
- [**Easy to use**]{.orange} with a variety of machine learning frameworks (scikit-learn, Keras, Pytorch...) 
::::

:::: {.fragment fragment-index=2}
```python
mlflow.sklearn.log_model(pipe_rf, "model")

mlflow.pyfunc.load_model(model_uri=f"models:/{model_name}/{version}")
y_train_pred = model.predict(X_train)

```
::::

:::: {.fragment fragment-index=3}
- What if we require greater [**flexibility**]{.orange}, e.g. to use a [**custom framework**]{.orange}?
::::

:::: {.fragment fragment-index=4}
- Possibility to [**track**]{.orange} , [**register**]{.orange} and [**deliver**]{.orange} your own model
::::

:::

## MLflow with a non standard framework 

::: {.nonincremental}

:::: {.fragment fragment-index=1}
- There are [**2 main differences**]{.orange} when using your own framework:
  - [**logging**]{.blue2} of parameters, metrics and artifacts
  - [**wrapping**]{.blue2} of your custom model so that MLflow can serve it
::::

:::: {.fragment fragment-index=2}
```python
# Define a custom model
class MyModel(mlflow.pyfunc.PythonModel):

    def load_context(self, context):
      self.my_model.load_model(context.artifacts["my_model"])

    def predict(self, context, model_input):
        return self.my_model.predict(model_input)
```
::::

:::

<!-- By creating a class that inherits from mlflow.pyfunc.PythonModel, you are essentially creating a wrapper around your custom model that allows it to be used with the MLflow platform. The mlflow.pyfunc.PythonModel class provides a standardized interface that makes it easy to integrate your custom model with the rest of the MLflow platform. -->

## From experiment towards production

- Notebooks are not suitable to build [**production-grade**]{.orange} ML systems:
  - Limited potential for [**automation**]{.blue2} of ML pipelines.
  - Lack of clear and [**reproducible**]{.blue2} workflows.
  - Hinders [**collaboration**]{.blue2} and [**versioning**]{.blue2} among team members.
  - Insufficient [**modularity**]{.blue2} for managing complex ML components.


```{python}
#| cache: false
import sys
sys.path.append("../src/")

import pandas as pd
import s3fs
import pyarrow.parquet as pq
from constants import TEXT_FEATURE, DATA_PATH
from preprocessor import Preprocessor

preprocessor = Preprocessor()
fs = s3fs.S3FileSystem(
    client_kwargs={"endpoint_url": "https://minio.lab.sspcloud.fr"}
)
df = pq.ParquetDataset(DATA_PATH, filesystem=fs).read_pandas().to_pandas()
df = df.sample(frac=0.001, random_state=0)

df_prepro = preprocessor.clean_text(df, TEXT_FEATURE)

ojs_define(data_raw = df, data_prepro = df_prepro)
```
