---
title: Une introduction au MLOps avec MLflow
subtitle: |
  [**[Romain Avouac (Insee), Thomas Faria (Insee), Tom Seimandi (Insee)]{.orange}**]{.orange}
slide-number: true
footer: |
  Une introduction au MLOps avec MLflow

lang: fr-FR
slide-tone: false
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
format:
  onyxia-revealjs:
    incremental: true 
    output-file: index.html
controls: true
css: ../custom.css
from: markdown+emoji
---

# Introduction

{{< include sections/0-introduction.qmd >}}

## Application 0 {.scrollable #app0}

{{< include applications/_application0.qmd >}}


# :one: Introduction à MLFlow

{{< include sections/1-mlflow-intro.qmd >}}

## Application 1

{{< include applications/_application1.qmd >}}

## Bilan

- `MLflow` simplifie le [**suivi**]{.orange} de l'entraînement de modèles
    - Garde [**trace**]{.blue2} des expérimentations et de leurs *outputs*
    - [**Intégration**]{.blue2} simple avec les principaux *frameworks* de ML

- [**Limites**]{.orange}
    - Comment utiliser des frameworks [***custom***]{.blue2} (non-nativement intégrés) ?
    - Comment passer de l'expérimentation à la [**mise en production**]{.blue2} ?



# :two: Un exemple concret

{{< include sections/2-mlflow-custom-class-example.qmd >}}


## Application 2 {.scrollable}

{{< include applications/_application2.qmd >}}

## Bilan

- `MLflow` est [**polyvalent**]{.orange}
    - Utilisation dee [**frameworks custom**]{.blue2} (modulo une [**classe "interface"**]{.blue2})
    - [**Industrialisation**]{.blue2} de l'entraînement (fichier `MLproject`)
    - [**Requêtage simple**]{.blue2} des modèles entraînés et stockés

- [**Limite**]{.orange} : le modèle entraîné n'est pas [**accessible**]{.blue2}
    - Requêtage simplifié... mais [**format non-pertinent**]{.blue2} pour tous les utilisateurs
    - Le modèle n'est [**pas déployé**]{.blue2}



# :three: Servir un modèle de ML à des utilisateurs

{{< include sections/3-deployment.qmd >}}

## Application 3 {.scrollable}

{{< include applications/_application3.qmd >}}

## Bilan



# :four: Machine learning en production

{{< include sections/4-ml-in-production.qmd >}}


## Application 4 {.scrollable}

{{< include applications/_application4b.qmd >}}

## Bilan



# :five: Distribuer l'optimisation des hyperparamètres

{{< include sections/5-parallel-training.qmd >}}


## Application 5 {.scrollable}

{{< include applications/_application5.qmd >}}


# Conclusion

{{< include sections/6-conclusion.qmd >}}
