---
title: An introduction to MLOps with MLflow
subtitle: |
  [**[Romain Avouac (Insee), Thomas Faria (Insee), Tom Seimandi (Insee)]{.orange}**]{.orange}
# date: 
slide-number: true
footer: |
  An introduction to MLOps with MLflow
# uncomment for French presentations:
# lang: fr-FR
# for blind readers:
slide-tone: false
# for @olevitt:
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
#multiplex: true
format:
  onyxia-revealjs:
    incremental: true 
    output-file: index.html
controls: true
css: ../custom.css
from: markdown+emoji
---

# Introduction

{{< include sections/0-introduction.qmd >}}

## Application 0 {.scrollable #app0}

{{< include applications/_application0.qmd >}}



# :one: Introduction to MLFlow

{{< include sections/1-mlflow-intro.qmd >}}

## Application 1

{{< include applications/_application1.qmd >}}

## Summary

- `MLflow` simplifies the [**tracking**]{.orange} of model training
    - Keeps [**record**]{.blue2} of experiments and their outputs
    - Simple [**integration**]{.blue2} with main ML frameworks

- [**Limitations**]{.orange}
    - How to use [**custom**]{.blue2} frameworks (non-natively integrated)?
    - How to move from experimentation to [**production**]{.blue2}?



# :two: A Practical Example

{{< include sections/2-mlflow-custom-class-example.qmd >}}

## Application 2 {.scrollable}

{{< include applications/_application2.qmd >}}

## Summary

- `MLflow` is [**versatile**]{.orange}
    - Use of [**custom frameworks**]{.blue2} (with a [**"interface" class**]{.blue2})
    - [**Industrialization**]{.blue2} of training (file `MLproject`)
    - [**Simple querying**]{.blue2} of trained and stored models

- [**Limitation**]{.orange}: the trained model is not [**accessible**]{.blue2}
    - Simplified querying... but [**irrelevant format**]{.blue2} for all users
    - The model is [**not deployed**]{.blue2}


# :three: Serving a ML model to users

{{< include sections/3-deployment.qmd >}}


## Application 3 {.scrollable}

{{< include applications/_application3.qmd >}}

## Summary


# :four: Machine learning in production

{{< include sections/4-ml-in-production.qmd >}}


## Application 4 {.scrollable}

{{< include applications/_application4b.qmd >}}

## Summary



# :five: Distributing the hyperparameter optimization

{{< include sections/5-parallel-training.qmd >}}

## Application 5 {.scrollable}

{{< include applications/_application5.qmd >}}


# Conclusion

{{< include sections/6-conclusion.qmd >}}
