apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: formation-mlops-api
spec:
  project: default
  source:
    repoURL: https://github.com/InseeFrLab/formation-mlops.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-formation
  syncPolicy:
    automated:
      selfHeal: true
